# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
# set -q __fish_home_manager_config_sourced; and exit
# set -g __fish_home_manager_config_sourced 1

# source /nix/store/85jcp4jrs1nmpj3i4yljpjv8vda2pr8g-hm-session-vars.fish/etc/profile.d/hm-session-vars.fish

# Source handler functions
source $XDG_CONFIG_HOME/fish/functions/__notify_long_cmd_preexec.fish
source $XDG_CONFIG_HOME/fish/functions/__notify_long_cmd.fish

if status is-login
    # Source /etc/profile on login. Copied from https://wiki.archlinux.org/title/Fish#Source_/etc/profile_on_login
    if not set -q __sourced_profile
        set -x __sourced_profile 1
        exec bash -c "\
            test -e /etc/profile && source /etc/profile
            test -e $HOME/.bash_profile && source $HOME/.bash_profile
            exec fish --login
        "
    end
    set -e __sourced_profile

    # put your other configs below

end

if status is-interactive
    # Abbreviations
    abbr --add -- .. 'cd ..'
    abbr --add -- ... 'cd ../..'
    abbr --add -- .... 'cd ../../..'

    abbr --add -- ls 'eza'
    abbr --add -- la 'eza -a'
    abbr --add -- ll 'eza -lh'
    abbr --add -- lla 'eza -lha'
    abbr --add -- lt 'eza --tree'

    abbr --add -- grep 'grep --color=auto'
    abbr --add -- egrep 'grep -E --color=auto'
    abbr --add -- fgrep 'grep -F --color=auto'
    abbr --add -- jctl 'journalctl -p 3 -xb'
    abbr --add -- history 'history --show-time='\''%F %T '\'''
    abbr --add -- tarnow 'tar -acf'
    abbr --add -- untar 'tar -zxvf'

    # Aliases
    alias eza 'eza --icons=always --color=always --group-directories-first --headers'

    # Interactive shell initialisation
    if test "$TERM" = xterm-kitty
        # Run fastfetch only when term is kitty (that means exclude vscode, ides, ...)
        fastfetch
    end

    # add completions generated by Home Manager to $fish_complete_path
    # begin
    #     set -l joined (string join " " $fish_complete_path)
    #     set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
    #     set -l post_joined (string replace $prev_joined "" $joined)
    #     set -l prev (string split " " (string trim $prev_joined))
    #     set -l post (string split " " (string trim $post_joined))
    #     set fish_complete_path $prev "/home/penguin/.local/share/fish/home-manager/generated_completions" $post
    # end
end
